name: Github secrets

on:
  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: print SEcret
        run: |
            echo "MY_TOP_SECRET: ${{ secrets.MY_TOP_SECRET }}"
            echo "i_dont_exist: ${{ secrets.i_dont_exist  }}"

      - name: print secret as an environment variables
        run: |
            echo 'MY_TOP_SECRET: ${{ secrets.MY_TOP_SECRET }}'
        env:
            MY_TOP_SECRET: ${{ secrets.MY_TOP_SECRET }}