name:

on: push

jobs:
    job_1:
        name: Upload Artifact
        runs-on: ubuntu-latest
        steps:
            -   name:
                run: echo "Hi, I am storing this data in this file, so that I can use this in the subsequent jobs within ths workflow run will upload this file to GitHub storage and download from there when needed in this woekflow run." > file.txt
            -   uses: actions/upload-artifact@v4
                with:
                    name: file
                    path: file.txt
    

    job_2:
        name: Download Artifact
        runs-on: ubuntu-latest
        needs: job_1
        steps:
            -   uses: actions/download-artifact@v2
                with:
                    name: file
            -   run: cat file.txt 