# This is a basic workflow to help you get started with Actions

name: 'Custom environment Vars'

# Controls when the workflow will run
on:
  

  workflow_dispatch:

env:
      DAY_OF_WEEK: Funday
      testvar: value-1
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  mainjob:
    # The type of runner that the job will run on
    name: 'Print the env vars'
    runs-on: ubuntu-latest

    env: 
      Greeting: Dear
      testvar: value-2

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: print-value-of-env-vars
        run: |
          echo "$Greeting $First_Name. today is $DAY_OF_WEEK!"
          echo "testvar $testvar"
          echo "testvar ${{ env.testvar }}"

        env:
          First_Name: Student
          testvar: value-3

      
      
