name: 'custom GITHUB_ENV var Demo'

on: workflow_dispatch


jobs:
    custom_GITHUB_ENV:
        runs-on: ubuntu-latest
        steps:
            - name: Set the value
            id: step_one
            run: 
                echo "action_state=yellow" >> $GITHUB-ENV
        
            -name: Use the value
            id: step_two
            run: 
                echo "${{ env.action-state }}"   



            

